version: '3'
services:
  db:
    image: postgres:13.3
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
  e2e:
    build:
      context: .
      dockerfile: Dockerfile.e2e
      args:
        DATABASE_URL: postgresql://root:password@db:5432/app-db?schema=public
    environment:
      DATABASE_URL: postgresql://root:password@db:5432/app-db?schema=public
    depends_on:
      - db
    ports:
      - '3000:3000'
